export const AUTH_USER_SUCCESSFUL = 'AUTH_USER_SUCCESSFUL';
export const AUTH_SIGNUP_SUCCESSFUL = 'AUTH_SIGNUP_SUCCESSFUL';
export const AUTH_USER_FAILURE = 'AUTH_USER_FAILURE';
export const AUTH_USER_LOGOUT = 'AUTH_USER_LOGOUT';

export const CREATE_CLOUDI = 'CREATE_CLOUDI';
export const CREATE_ALBUM = 'CREATE_ALBUM';
export const ERROR_CREATE_CLOUDI = 'ERROR_CREATE_CLOUDI';
export const ERROR_CREATE_ALBUM = 'ERROR_CREATE_ALBUM';
export const GET_ALL_CLOUDIS = 'GET_ALL_CLOUDIS';
export const GET_CLOUDI_BY_ID = 'GET_CLOUDI_BY_ID';

export const GET_ALL_USER_CLOUDIS = 'GET_ALL_USER_CLOUDIS';

export const DELETE_USER_CLOUDI_BY_ID = 'DELETE_USER_CLOUDI_BY_ID';